### ISSUE TITLE
Присваивается одно и тоже значение SETTINGS_APPMILUR_T1

### ISSUE THREAD

**Issue by Silowar** [directman66/majordomo-milur#1]
625 и 626 строки:
if (!isset($t1)) {sg($objname.".t1",SETTINGS_APPMILUR_T1);}
if (!isset($t2)) {sg($objname.".t2",SETTINGS_APPMILUR_T1);}
Присваивается одно и тоже значение SETTINGS_APPMILUR_T1

**Comment by tarasfrompir** [comment]
тоже и 375-376 строках
